DROP TABLE IF EXISTS comments;

CREATE TABLE comments(
	id SERIAL PRIMARY KEY,
	comment TEXT,
	username VARCHAR(255) NOT NULL,
    img_id INTEGER NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
